### ISSUE TITLE
Releases without album art causes exception error

### ISSUE THREAD

**Issue by BlueCrystal** [mreweilk/RedSea#5]
Some releases are still causing the script to die and throw an exception error when tagging. This occurs when there is no album art on the release or track you rip. If there is no album art, the art tagging should just be skipped for the track and the ripping should continue.

Example release: https://listen.tidal.com/track/75617724
Here's the exception:
```
Traceback (most recent call last):
  File "/home/aoichan/RedSea/redsea.py", line 114, in <module>
    main()
  File "/home/aoichan/RedSea/redsea.py", line 81, in main
    _, filepath = md.download_media(track, config['tidal']['quality'])
  File "/home/aoichan/RedSea/mediadownloader.py", line 141, in download_media
    if not self._dl_picture(track_info['album']['cover'], aa_location):
  File "/home/aoichan/RedSea/mediadownloader.py", line 43, in _dl_picture
    return self._dl_url(TidalApi.get_album_artwork_url(album_id), where)
  File "/home/aoichan/RedSea/mediadownloader.py", line 30, in _dl_url
    total = int(r.headers['content-length'])
  File "/home/aoichan/.local/lib/python3.5/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

Edit: After further inspection, it appears Tidal does have the album art, but the site doesn't say so. I'm not sure if it's still a cover problem or what, but that seems to be the issue. Also, the cover is attached to the tracks, but it is not downloaded to the folder.

`

**Comment by mreweilk** [comment]
https://github.com/mreweilk/RedSea/commit/0971995c19c84719f48ff306242731db698e0e54
